echo "Make sure you uninstall system assimp"
cd $NODEIN/vsg/VulkanSceneGraph; rm -rf debug; mkdir -p debug; cd debug; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/debug ..; make -j20; make install
cd $NODEIN/vsg/vsgXchange;       rm -rf debug; mkdir -p debug; cd debug; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/debug ..; make -j20; make install
cd $NODEIN/vsg/vsgImGui;         rm -rf debug; mkdir -p debug; cd debug; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/debug ..; make -j20; make install
cd $NODEIN/vsg/vsgExamples;      rm -rf debug; mkdir -p debug; cd debug; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/debug ..; make -j20; make install
#cd $NODEIN/vsg/vsgCs;            mkdir -p debug; cd debug; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/debug ..; make -j20; make install

cd $NODEIN/vsg/VulkanSceneGraph; rm -rf release; mkdir -p release; cd release; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/release ..; make -j20; make install
cd $NODEIN/vsg/vsgXchange;       rm -rf release; mkdir -p release; cd release; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/release ..; make -j20; make install
cd $NODEIN/vsg/vsgImGui;         rm -rf release; mkdir -p release; cd release; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/release ..; make -j20; make install
cd $NODEIN/vsg/vsgExamples;      rm -rf release; mkdir -p release; cd release; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/release ..; make -j20; make install
#cd $NODEIN/vsg/vsgCs;            mkdir -p release; cd release; cmake -DCMAKE_TOOLCHAIN_FILE=$NODEIN/nodelab/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$NODEIN/usr/release ..; make -j20; make install
